### ISSUE TITLE
Opis interfejsów komponentów systemu

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#36]
W kolaboracji z @PrzemekBurczyk 

Przedmiotem issue jest opisanie metod i eventów emitowanych przez każdy z komponentów systemu opisanych w architekturze. Wynikiem powinna być nowa sekcja w artykule https://github.com/TheTaz/IO2014/wiki/Architektura-systemu

**Comment by rslota** [comment]
Opis interfejsów jest tylko poglądowy, ma dać zarys odpowiedzialności modułów. Nie sposób przewidzieć wszystkiego, więc jeśli ktoś podczas pisania zauważy, że czegoś brakuje, proszę nie mówić "eee tam, nie było w Architekturze Systemu -olewam". Nie, to tak nie działa. Piszemy tak żeby było fajnie :)
