### ISSUE TITLE
"Bezprotokołowe" połączenie klient-serwer [2]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#4]
Po otwarciu strony serwera w przeglądarce Connection Manager https://github.com/TheTaz/IO2014/issues/3 powinien zarejestrować nowego klienta i przesłać mu jakąś prostą informację ("Hello World") która wyświetli się na stronie.

**Comment by maciekbb** [comment]
Sądzę, że można to uznać za wykonane.
