### ISSUE TITLE
Research odnośnie narzędzia do automatyzacji testów akceptacyjnych

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#41]
Jasmine jest świetny do unit testów, ale prawdopodobnie potrzebne nam coś innego do testów akceptacyjnych. Reasearch: czy i co.

**Comment by sheiffa** [comment]
Spojrzałem na kilka framework'ów i najkorzystniejszy wydaje mi się Zombie.js. Będzie można go używać razem z Jasmine:

http://krasimirtsonev.com/blog/article/Testing-with-headless-browser-Zombiejs-Jasmine-TDD-NodeJS-example

**Comment by maciekbb** [comment]
Ja bym się przyjrzał raczej http://webdriver.io/

2014-04-07 22:33 GMT+02:00 sheiffa notifications@github.com:

**Comment by maciekbb** [comment]
Można używać składni w stylu jasmine + http://phantomjs.org/ (żeby
przeglądarka nie musiała być otwierana w celu przeprowadzenia testu)

W dniu 8 kwietnia 2014 11:01 użytkownik Maciek Wątroba
maciek.bb@gmail.comnapisał:

**Comment by TheTaz** [comment]
Co do webdrivera to bawiłem się nim kiedyś i jest bardzo prosty i fajny w
obsłudze, a przy tym efektywny.

W dniu 8 kwietnia 2014 11:03 użytkownik Maciej Wątroba <
notifications@github.com> napisał:

**Comment by sheiffa** [comment]
Dodałem na wiki opis jak skonfigurować tego Webdrivera oraz jak będziemy umieszczać i uruchamiać testy.
