### ISSUE TITLE
Dokumentacja faz przetwarzania grunta [2]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#45]
Obrazek + opis co grunt u nas robi kiedy instalujemy / uruchamiamy aplikację. Wynikiem powinna być sekcja w dokumencie https://github.com/TheTaz/IO2014/wiki/Budowanie-i-%C5%9Brodowisko .

**Comment by TheTaz** [comment]
https://github.com/TheTaz/IO2014/wiki/Budowanie-i-%C5%9Brodowisko#3-fazy-przetwarzania-grunta

Taki rysunek ma być ?

**Comment by kzemek** [comment]
@TheTaz Mniej-więcej. Fajnie by było zaznaczyć tam w którym momencie zadaniami zajmuje się grunt.

**Comment by TheTaz** [comment]
Ok już robie.

W dniu 4 maja 2014 22:30 użytkownik Konrad Zemek
notifications@github.comnapisał:

**Comment by TheTaz** [comment]
Tak to ma wyglądać teraz ?

**Comment by kzemek** [comment]
Wydaje mi się, że tyle wystarczy na rysunku.

**Comment by TheTaz** [comment]
Ok zaraz kończe opis.

W dniu 4 maja 2014 22:42 użytkownik Konrad Zemek
notifications@github.comnapisał:

**Comment by TheTaz** [comment]
https://github.com/TheTaz/IO2014/wiki/Budowanie-i-%C5%9Brodowisko

Tak to obecnie wygląda - poprawiłem rysunek, wszystko jest teraz tak jak ma być po kolei. Wydaje mi się że więcej nie trzeba pisać/rysować.
