### ISSUE TITLE
Zaprojektowanie protokołu klient - serwer [4]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#46]
Opisanie sposobu komunikacji klienta z serwerem oraz tego jak klient będzie obsługiwał otrzymane dane. Wynikiem powinna być kolejna sekcja w https://github.com/TheTaz/IO2014/wiki/Architektura-systemu .

**Comment by rslota** [comment]
https://github.com/TheTaz/IO2014/wiki/Architektura-systemu
