### ISSUE TITLE
Implementacja protokołu klient - serwer [3]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#47]
Implementacja protokołu i funkcji opisanych przez https://github.com/TheTaz/IO2014/issues/46 .

**Comment by PrzemekBurczyk** [comment]
Na nowym branchu: [https://github.com/TheTaz/IO2014/tree/47_client_server_protocol](https://github.com/TheTaz/IO2014/tree/47_client_server_protocol) zaimplementowałem skrypt, który będzie się zajmował komunikacją po stronie client.html. Sam skrypt umieściłem w oddzielnym pliku public/scripts/client.js, napisałem prosty przykład komunikacji, żeby sprawdzić czy działa (w server.coffee -> initializeConnectionManager), będzie on jednak usunięty, jako że po stronie serwera się jeszcze trochę zmieni. 
Mam natomiast kilka pytań/wątpliwości:
1. Skrypty dla klientów/adminów (wykonywane po stronie przeglądarki) trzymamy jako js w public, czy też pisać je w coffee i podczas uruchamiania kompilować do js i przenosić do public?
2. Który element architektury odbiera jako pierwszy eventy od klientów? Connection manager?
Jeśli tak, to jeszcze dopiszę w nim podstawową obsługę eventów ack, error i result. 
3. Do komunikacji klient -> serwer używamy kilku typów eventów? (Obecnie mam ack, error, jobResult). Obecna architektura wiadomości trochę bardziej wygląda jakby cała komunikacja szła po 1 typie eventu, a rodzaj eventu jest rozpoznawany po zawartości wiadomości.
4. Czy dobrze rozumiem, że opcode [1-3] są operacjami od serwera dla klienta, a opcode 4 od klienta dla serwera?
5. Czy dobrze rozumiem przykładową komunikację serwer <-> klient:
- serwer wysyła opcode = 1, msgId = 1 oraz zadanie do wykonania
- klient zapisuje zadanie i wysyła ack = true, msgId = 1

natomiast:
- klient wykonał zadanie i przesyła wynik: opcode = 4, msgId = -1
- serwer odbiera wynik i wysyła ack = true, msgId = -1
  ?

Po poprawkach i uzyskaniu odpowiedzi na pytania zrobię pull requesta :)

**Comment by kzemek** [comment]
Ja mogę odpisać na 1: piszemy w CoffeeScripcie. Fajnie by było wrzucić do naszego projektu https://github.com/adunkman/connect-assets i tego używać, ale jak wolisz.

EDIT: Ok, nie jak wolisz. Życzę sobie connect-assets. :P Katalog /assets/ i śmiga.

**Comment by rslota** [comment]
Ad1. CoffeeScript FTW.

**Comment by rslota** [comment]
Ad2. Chyba ConnectionManager powinien obsługiwać takie rzeczy.

**Comment by rslota** [comment]
Ad3. Pisząc to zakładałem komunikację po czystym binarnym połączeniu WebSocket. Z tego co rozumiem mamy dostęp do bardziej wyrafinowanych protokołów, więc jeśli możemy sterować typami eventów, to zdecydowanie można a nawet należy użyć ich do sterowania typem wiadomości. Tj. ACK, Error, NormalMsg.

**Comment by rslota** [comment]
Ad4. Tak wynika z ich sementyki.

**Comment by rslota** [comment]
Ad5. Tak.

**Comment by maciekbb** [comment]
Ad2. Nie widzę problemu, żebyś dopisał potrzebne Ci funkcje. Rzuć tylko okiem na #66

**Comment by PrzemekBurczyk** [comment]
OK! Myślę, że późniejszym popołudniem dokończę jeszcze implementację i do końca dnia powinien być pull request.

**Comment by PrzemekBurczyk** [comment]
Jest update, jeszcze dopiszę doc'i do pozostałych metod i będzie pull request.
Dopisałem odpowiednie funkcje w connection managerze i prosty stub obsługi eventów (logi).
W server.coffee jest prosty przykład że działa (i jak działa)

**Comment by PrzemekBurczyk** [comment]
@kzemek nie zauważyłem Twojego edita, jeszcze nie ma connect-assets, skrypt po kompilacji jest wrzucany do public/scripts
