### ISSUE TITLE
Stworzenie "konsoli" administratora [2]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#5]
Administrator może w jakiś sposób (przeglądarka, konsola?) podłączyć się do serwera i dostać od niego znak zachęty dla administratora.

**Comment by PrzemekBurczyk** [comment]
Jako, że [#27](https://github.com/TheTaz/IO2014/pull/27) został już wprowadzony do developementu, można chyba uznać, że konsola na chwilę obecną już istnieje w swojej podstawowej formie.
