### ISSUE TITLE
Pełna implementacja API Job Dispatcher [4]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#51]
Implementacja API opisanego w https://github.com/TheTaz/IO2014/wiki/Architektura-systemu .

**Comment by sheiffa** [comment]
Implementację mam zacząć dopiero jak gałąź Przemka ( https://github.com/TheTaz/IO2014/tree/47_client_server_protocol ) zostanie scalona z development, czy mam utworzyć podgałąź do jego gałęzi i już zacząć?

**Comment by kzemek** [comment]
@sheiffa Już zacznij.
