### ISSUE TITLE
Opis działania w projekcie [2]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#60]
Krótki schemat "flow" projektu - piszesz kod, jest review, co się dzieje jak przechodzi, co jak nie, etc. Efektem powinna być sekcja w https://github.com/TheTaz/IO2014/wiki/Zasady-prowadzenia-projektu

**Comment by maciekbb** [comment]
Dokument został uaktualniony https://github.com/TheTaz/IO2014/wiki/Zasady-prowadzenia-projektu, jeśli czegoś brakuje to proszę o uwagi. @kzemek

**Comment by kzemek** [comment]
> General workflow

Ogólny workflow... Nie wiem, w każdym razie niepotrzebnie tak angielsko w dokumencie po polsku.

> Jeśli powstają konflikty musimy je rozwiązać przez domergowanie development do naszej gałęzi i uaktualnienie pull requesta

"domergowanie"? :P merge gałęzi development

> Kod musi zostać zrecenzowany przez kogoś z zespołu, jeśli uważamy, że konkretna osoba powinna to zrobić (np. nasza praca jest sprężona z jej), otagujmy ją w opisie PR.

Sprzężona

> Hints

Wskazówki? :)

Poza drobnostkami nie widzę problemów.

**Comment by maciekbb** [comment]
Ok, poprawione.
