### ISSUE TITLE
Pasek postępu w "konsoli" administratora [3]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#61]
Paski w konsoli powinny się ruszać i ich ruch powinien odpowiadać rzeczywistości.

**Comment by PrzemekBurczyk** [comment]
Branch [https://github.com/TheTaz/IO2014/tree/61_progress_bars](https://github.com/TheTaz/IO2014/tree/61_progress_bars) w commicie z tagiem DEMO ma ładny pokaz ruszających się pasków, gdyby ktoś chciał sobie zobaczyć.
