### ISSUE TITLE
Recenzja dokumentu: Architektura systemu [2]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#79]
Przeczytać, zobaczyć czy wszystko jest i jest zrozumiałe, napisać w komentarzach co trzeba poprawić. Task powinien być zakończony gdy dokument zostanie poprawiony przez autora.

**Comment by sheiffa** [comment]
Brakuje parametrów dla metod w podanych interfejsach.

**Comment by sheiffa** [comment]
Na diagramie brakuje nowo dodanej zależności między JobDispatcher a JsInjector.

**Comment by sheiffa** [comment]
Trzeba dodać do interfesju injectora signal onPeerCapabilitiesChanged.

**Comment by sheiffa** [comment]
Można zrobić kosmetyczną zmianę - na sam początek artykułu dać obrazek, potem opis interfejsów a na koniec opis protokołu - będzie bardziej logiczne uporządkowanie biorąc pod uwagę temat artykułu.

**Comment by PrzemekBurczyk** [comment]
Zaktualizowałem opis protokołu, tak by odzwierciedlał faktycznie to co się dzieje w kodzie (tj. eventy zamiast opcodes)
