### ISSUE TITLE
Stworzenie Job Dispatchera [3]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#8]
Job Dispatcher dostaje argumenty funkcji do obliczenia na klientach, funkcję dzielącą te argumenty na mniejsze części, listę podłączonych klientów od Connection Managera https://github.com/TheTaz/IO2014/issues/3 i zleca Connection Managerowi "wyślij temu klientowi te argumenty". Issue wymaga odpowiednich modyfikacji Connection Managera. Komunikacja z klientem nie musi być zaimplementowana.

**Comment by kzemek** [comment]
Tu jest przykładowy task:
https://github.com/TheTaz/IO2014/blob/b04874496e8b439a7745e0be54480dc2273938c5/example_task.js

Job dispatcher na wejściu dostanie obiekt TaskParams, funkcję taskSplit i listę podłączonych klientów.

**Comment by kzemek** [comment]
Wróć; listę podłączonych klientów powinien wziąć sobie sam za pomocą API Connection Managera. Jeżeli takiego nie ma - trzeba dodać.

**Comment by maciekbb** [comment]
@kzemek jest taka metoda (zwraca sockety podłączonych klientów). Jeśli trzeba by było w niej coś zmienić to dajcie znać.

**Comment by kzemek** [comment]
@maciekbb Connection Manager miał jeszcze rozróżniać między hostami i procesami na hostach. Czy zwracany socket oferuje nam coś takiego?

**Comment by maciekbb** [comment]
@kzemek nie wyobrażam sobie chwilowo jak by to miało wyglądać, gdyż to TaskDispatcher czeka na odpowiedź od klienta i wie kiedy proces na danym hoście się skończył.

**Comment by kzemek** [comment]
@maciekbb Powinno wyglądać tak jak w architekturze systemu: https://github.com/TheTaz/IO2014/wiki/Architektura-systemu . Nie wiem jakie możliwości daje socket.io, ale to jest prawdopodobnie kwestia grupowania socketów po ich adresie IP - to są procesy z jednego hosta. Inne moduły nie potrzebują dostawać socketów, bo to zadaniem ConnectionManagera jest komunikować się z klientami; inne moduły potrzebują tylko jakąś reprezentację hostów i procesów zrozumiałą dla CM.
