### ISSUE TITLE
Recenzja dokumentu: Budowanie i środowisko [2]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#80]
Przeczytać, zobaczyć czy wszystko jest i jest zrozumiałe, napisać w komentarzach co trzeba poprawić. Task powinien być zakończony gdy dokument zostanie poprawiony przez autora.

**Comment by kzemek** [comment]
1: Zależności do uzupełnienia (też: ibrik)
3.2: lista zależności jest tu niepotrzebna, klonuje punkt 1

**Comment by TheTaz** [comment]
Co do 3.2 to on chciał żeby tak było, w sensie Dębski ^^.

**Comment by TheTaz** [comment]
Ale mogę skasować - nie ma sprawy w sumie - bo racja jakby na to nie patrzeć - to jest klon 1.

**Comment by TheTaz** [comment]
Poprawione.
