### ISSUE TITLE
Recenzja dokumentu: Historyjki użytkownika i testy akceptacyjne [2]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#81]
Przeczytać, zobaczyć czy wszystko jest i jest zrozumiałe, napisać w komentarzach co trzeba poprawić. Task powinien być zakończony gdy dokument zostanie poprawiony przez autora.

**Comment by TheTaz** [comment]
Po pierwsze to trzeba uzupełnić wszystkie historyjki - jaki tam ma być przebieg :). Potem będę recenzował dalej.
