### ISSUE TITLE
Recenzja dokumentu: Metody testowania [2]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#82]
Przeczytać, zobaczyć czy wszystko jest i jest zrozumiałe, napisać w komentarzach co trzeba poprawić. Task powinien być zakończony gdy dokument zostanie poprawiony przez autora.

**Comment by maciekbb** [comment]
`jasmine-node` jest zadeklarowany w zależnościach w `package.json`, a więc sposób jego instalacji jest błędnie opisany.

**Comment by maciekbb** [comment]
Czy zamiast pisać za każdym razem `browser=chrome npm run-script accept` nie lepiej byłoby napisać, żeby dodać do `.bashrc` (dla windowsa coś innego pewnie) `export browser=phantom`? Przy czym zamiast `browser` użyłbym nazwy w stylu `ACCAPTANCE_TESTS_BROWSER`

**Comment by maciekbb** [comment]
Brakuje mi jakiegoś opisu co oznacza fakt, że klasa (bądź funkcja systemu) została przetestowana. 

Jednym z rozwiązań mogłoby być wprowadzenie jakiegoś narzędzia do mierzenia pokrycia kodu testami, a czym rozmawialiśmy ostatnio.

**Comment by maciekbb** [comment]
Myślę, że do każdej sekcji można byłoby dodać przykładowe testy.
