### ISSUE TITLE
Recencja dokumentu: Plan [1]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#83]
Przeczytać, zobaczyć czy wszystko jest i jest zrozumiałe, napisać w komentarzach co trzeba poprawić. Task powinien być zakończony gdy dokument zostanie poprawiony przez autora.

**Comment by TheTaz** [comment]
Plan trzeba uzupełnić o ilość punktów, które przydzieliliśmy do każdego sprintu, oraz przydałoby się uzupełnić też treść mając na względzie podane issue.
