### ISSUE TITLE
Recencja dokumentu: Podręcznik użytkownika [2]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#84]

**Comment by PrzemekBurczyk** [comment]
Uzupełniłem podręcznik o informacje dotyczące dodawania zadań i wyświetlania wyników. Gdy system będzie gotowy, umieszczę jeszcze przykładowy działający task i może jakiś zrzut panelu z podpisami co gdzie jest.

**Comment by kzemek** [comment]
2.3: Należy dodać, że szczegółowe informacje o strukturze tasku można znaleźć w dokumencie "..."
3.1: Dodać co się dzieje po podłączeniu, tj. że automatycznie stajemy się częścią "chmury obliczenowej" i możemy wyjść przez zamknięcie zakładki.

**Comment by PrzemekBurczyk** [comment]
Done.
