### ISSUE TITLE
Stworzenie JS Injectora [3]

### ISSUE THREAD

**Issue by kzemek** [TheTaz/IO2014#9]
JS Injector dostaje funkcję która ma być uruchamiana na klientach i listę podłączonych klientów, i zleca Connection Managerowi https://github.com/TheTaz/IO2014/issues/3 "wyślij temu klientowi tę funkcję". Dodatkowo upewnia się, że funkcja została zainstalowana (obsługa ACKa od klienta). Issue wymaga odpowiednich modyfikacji Connection Managera. Komunikacja z klientem nie musi być zaimplementowana.

**Comment by kzemek** [comment]
Przykładowy task:
https://github.com/TheTaz/IO2014/blob/b04874496e8b439a7745e0be54480dc2273938c5/example_task.js

JS Injector dostanie funkcję taskProcess którą musi powysyłać. Listę podłączonych klientów powinien wziąć sobie sam za pomocą API Connection Managera.

**Comment by maciekbb** [comment]
Mam dwa pytania co do tego i #6:
1. Czy funkcje split i merge nie mogłyby być bardziej generyczne i odpowiednie dla całej klasy problemów?
2. Czy Task nie mógłby być klasą implementującą z góry ustalony interfejs?

**Comment by rslota** [comment]
1. Nie mogą być bardziej generyczne, ponieważ nie wiemy jak podzielić zadanie które nawet nie wiemy jak wygląda i na czym polega. Tym bardziej nie wiemy z czym się je argumenty dla tego zadania.
2. Jestem koniem.

**Comment by maciekbb** [comment]
Jeszcze jedno- czy potrzebujemy podział na JSInjector i TaskDispatcher?

**Comment by kzemek** [comment]
@maciekbb Zadaniem JSInjectora jest zapewnienie, że każdy klient - w szczególności ten, który dopiero się podłączył - wie jaki task ma wykonać. Zadaniem JobDispatcher jest zapewnienie, że klient ma odpowiednie argumenty dla swojego taska, w szczególności może dostać wiele różnych zestawów argumentów w różnym czasie.

JSInjector przejmuje się jednym, JobDispatcher przejmuje się drugim. O ile logika pierwszego raczej nam nie wybuchnie, to JobDispatcher może się znacznie w środku pokomplikować w miarę jak będziemy implementować bardziej skomplikowane podejścia do problemu. Single responsibility principle.
