### ISSUE TITLE
Aktualizacja połaczenia JobDispatchera z Injectorem i Connection Managerem. Implementacja odwzorowania socket-job. Refaktoryzacja - utworzenie klas Job i TaskCollection. [2]

### ISSUE THREAD

**Issue by rslota** [TheTaz/IO2014#93]
Aktualizacja JobDispatchera.

**Comment by sheiffa** [comment]
Dodanie referencji do Code Injectora. Refaktoryzacja wywołań getPeerCapabilities. Przekazanie callbacków do Connection Managera. Dodanie odwzorowania socket - job. Refaktoryzacja - utworzenie klas Job i TaskCollection

**Comment by sheiffa** [comment]
@kzemek @RoXeon czy mam zostawić na razie metodę stopTask(taskId) w takiej formie w jakiej jest - czyli z wywołaniem niezaimplementowanej metody connection managera deleteJobFromPeer? Czy mam zamienić to na wywołanie zaimplementowanej już metody deleteTaskFromPeer dla odpowiednich peerów? Były co do tego wątpliwości i nie pamiętam na czym stanęło.

**Comment by kzemek** [comment]
@sheiffa Zmień nazwę metody na `stopJob(taskId, jobId)` i wszystko co z tym związane, ale poza tym tak, wywołuj stubowaną implementację w `ConnectionManager`.

**Comment by sheiffa** [comment]
Zrobione, pozostało mi tylko zrefaktoryzować testy i zrobię pull request.
